name = "EBMPackage"
uuid = "800201b8-1818-40c2-aea5-cf0d9e8bc7c9"
authors = ["SieglStefan <stefan.siegl02@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
